# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27968d19127cdb4cae5d786e334a8db5728d70c7d5818a4919618272a647d3cd6c807023c3e5bff775083bdf543a756dc9bf6237e90776c2e586e678e59429fb

test:
  secret_key_base: 628fa747c7597d0dbbea2cdb9264fd02b572fb8205a8df6412fe708cde3243cd79329698319f4e54d8ce326827b385772681b07aeff251070954738cd7befb07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
